Scaling of a Discrete Log Language
dwallet-labs/enhanced-maurer pull request #14
Opened 2024-07-24 10:43 UTC by ycscaly

This PR implements the Scaling of Discrete Log Language

2024-07-24 11:51 UTC, dolevmu approved these changes
Looks good to me, but it would be easier for people to verify your code if you add the annotations.

2024-07-24 11:51 UTC, dolevmu commented on src/scaling_of_discrete_log.rs
> +pub struct Language<
Let's add like we did with after the audit, in the comments a mapping between the variable names in the code and in the paper. Also let's describe the language definition here mathematically as well.

2024-07-24 11:51 UTC, dolevmu commented on src/scaling_of_discrete_log.rs
> +        // no mask needed, as we don't need circuit privacy.
Now that I'm reading it, I think we should be a bit more careful/clear:
```suggestion
        // No masking of the plaintext is needed, as we don't need secure function evaluation.
        // However, we do want to re-randomize the ciphertext when doing the scalar multiplication, to ensure circuit privacy against an adversary that does not hold the private key, that is, the centralised party A.
```
I think the same comment should also be changed in EncDH if I remember correctly.

2024-07-31 12:38 UTC, ofirfriedman42 approved these changes

2024-08-18 09:00 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +/// if we use this language in its enhanced form, i.e. `EnhancedLanguage`.
```suggestion
/// if we use this language in its enhanced form, i.e., `EnhancedLanguage`.
```

2024-08-18 09:07 UTC, zeevmoney requested changes
see comments, also, there is a lot of duplicate code taken from encryption of discrete log, can you move it to functions so we won't have to maintain the same code in two different places?

2024-08-18 09:07 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +/// that is not a secure function evaluation. That is, the result is not safe to decrypt, as it does
```suggestion
/// Furthermore, even when using `EnhancedLanguage`, note that `ENC_DH` proves a correct computation
/// that is not a secure function evaluation. That is, the result is unsafe to decrypt, as it does
```

2024-08-18 09:07 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +/// only assure security for groups and encryption schemes for which we know how to prove it.
```suggestion
/// However, knowledge-soundness proofs are group and encryption scheme-dependent, and thus we can
/// only ensure security for groups and encryption schemes for which we know how to prove it.
```

2024-08-18 09:07 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +/// In regards to additively homomorphic encryption schemes, we proved it for `paillier`.
```suggestion
/// Regarding additively homomorphic encryption schemes, we proved it for `Paillier`.
```

2024-08-18 09:07 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +/// e.g. by verifying (and following) a sequence of enhanced proofs over the homomorphic
```suggestion
/// e.g., by verifying (and following) a sequence of enhanced proofs over the homomorphic
```

2024-08-18 09:07 UTC, zeevmoney commented on src/scaling_of_discrete_log.rs
> +    RandomnessSpaceGroupElement: group::GroupElement,
```suggestion
    PlaintextSpaceGroupElement: GroupElement,
    RandomnessSpaceGroupElement: GroupElement,
```
no need to fix prefix everywhere.

2024-09-05 13:00 UTC, ycscaly commented
Annotations should be added across the board, let's do that in a separate PR

2024-09-05 13:05 UTC, merged